#pragma once
#include <stdint.h>

#define MAX_ASSETS 100
#define MAX_DATA 100
#define MAX_PLAYERS 5
#define MAX_ENEMIES 200
#define MAX_PROJECTILES 200
#define MAX_COLLECTIBLES 200
#define MAX_ENTITIES (MAX_PLAYERS + MAX_ENEMIES + MAX_PROJECTILES + MAX_COLLECTIBLES)

// ENTITY TYPE RANGES
#define ENEMIES_START (MAX_PLAYERS)
#define ENEMIES_END (ENEMIES_START + MAX_ENEMIES - 1)
#define PROJECTILES_START (ENEMIES_START + MAX_ENEMIES)
#define PROJECTILES_END (PROJECTILES_START + MAX_PROJECTILES - 1)
#define COLLECTIBLES_START (PROJECTILES_START + MAX_PROJECTILES)
#define COLLECTIBLES_END (COLLECTIBLES_START + MAX_COLLECTIBLES - 1)

#define GROUND_FRICTION 0.85f
#define WALL_FRICTION 0.8f
#define AIR_FRICTION 0.98f
#define TILE_SIZE 64

#define MAX_MAX_HEIGHT 100
#define MAP_MAX_WIDTH 300
#define MAP_MAX_LENGTH (MAX_MAX_HEIGHT * MAP_MAX_WIDTH)


